#!/usr/bin/env python3
"""Export trained Keras model to TFLite INT8 and C header for firmware.

Usage:
    python scripts/export_tflite.py --config configs/default.yaml
    python scripts/export_tflite.py --config configs/default.yaml --model outputs/best_model.keras
"""

import argparse
import os
import struct
import sys
from pathlib import Path

os.environ.setdefault("TF_USE_LEGACY_KERAS", "1")

import numpy as np
import tensorflow as tf
import yaml


def representative_dataset_gen(data_path: Path, n_samples: int = 200):
    """Generator for calibration data (required for full INT8 quantization)."""
    X = np.load(data_path / "X_train.npy")
    indices = np.random.choice(len(X), size=min(n_samples, len(X)), replace=False)
    for i in indices:
        yield [X[i:i+1].astype(np.float32)]


def export_tflite(model_path: str, data_path: Path, output_path: str,
                  quantize_int8: bool = True) -> bytes:
    """Convert Keras model to TFLite, optionally with INT8 quantization."""
    import tf_keras as keras
    model = keras.models.load_model(model_path, compile=False)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    if quantize_int8:
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = lambda: representative_dataset_gen(data_path)
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.int8
        converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    with open(output_path, "wb") as f:
        f.write(tflite_model)

    return tflite_model


def tflite_to_c_header(tflite_bytes: bytes, c_array_name: str, output_path: str):
    """Convert TFLite model bytes to a C header file."""
    hex_lines = []
    for i in range(0, len(tflite_bytes), 12):
        chunk = tflite_bytes[i:i+12]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        hex_lines.append(f"  {hex_str},")

    header = f"""// Auto-generated by export_tflite.py — do not edit
// Model size: {len(tflite_bytes)} bytes ({len(tflite_bytes)/1024:.1f} KB)

#ifndef BEAT_MODEL_DATA_H
#define BEAT_MODEL_DATA_H

alignas(8) const unsigned char {c_array_name}[] = {{
{chr(10).join(hex_lines)}
}};

const unsigned int {c_array_name}_len = {len(tflite_bytes)};

#endif // BEAT_MODEL_DATA_H
"""
    with open(output_path, "w") as f:
        f.write(header)


def main():
    parser = argparse.ArgumentParser(description="Export model to TFLite INT8 C header")
    parser.add_argument("--config", default="configs/default.yaml")
    parser.add_argument("--model", default="outputs/best_model.keras", help="Trained model path")
    parser.add_argument("--data-dir", default=None, help="Processed data dir (for calibration)")
    parser.add_argument("--output-dir", default="outputs", help="Output directory")
    parser.add_argument("--no-quantize", action="store_true", help="Skip INT8 quantization")
    args = parser.parse_args()

    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    data_dir = Path(args.data_dir or cfg["data"]["processed_dir"])
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    model_path = args.model
    if not Path(model_path).exists():
        print(f"Error: Model not found at {model_path}", file=sys.stderr)
        sys.exit(1)

    max_size_kb = cfg["export"]["max_model_size_kb"]
    c_array_name = cfg["export"]["c_array_name"]
    header_path = cfg["export"]["output_header"]

    # Export TFLite
    quantize = not args.no_quantize
    tflite_path = str(output_dir / ("beat_model_int8.tflite" if quantize else "beat_model_fp32.tflite"))

    print(f"Exporting {'INT8' if quantize else 'FP32'} TFLite model...")
    tflite_bytes = export_tflite(model_path, data_dir, tflite_path, quantize_int8=quantize)

    size_kb = len(tflite_bytes) / 1024
    print(f"TFLite model: {size_kb:.1f} KB ({tflite_path})")

    if size_kb > max_size_kb:
        print(f"WARNING: Model ({size_kb:.1f} KB) exceeds budget ({max_size_kb} KB)!", file=sys.stderr)
        print("Consider reducing channels or layers.", file=sys.stderr)
        sys.exit(1)

    # Export C header
    Path(header_path).parent.mkdir(parents=True, exist_ok=True)
    tflite_to_c_header(tflite_bytes, c_array_name, header_path)
    print(f"C header: {header_path}")

    # Validate by loading
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    print(f"\nModel validation:")
    print(f"  Input:  {input_details[0]['shape']} dtype={input_details[0]['dtype']}")
    print(f"  Output: {output_details[0]['shape']} dtype={output_details[0]['dtype']}")

    # Estimate firmware memory
    tensor_arena_kb = sum(
        np.prod(d["shape"]) * np.dtype(d["dtype"]).itemsize
        for d in interpreter.get_tensor_details()
    ) / 1024
    print(f"  Estimated tensor arena: ~{tensor_arena_kb:.1f} KB")


if __name__ == "__main__":
    main()
