// Auto-generated by export_tflite.py — do not edit
// Placeholder stub — replace with trained OnsetNN model
// Expected: Conv1D, W8, 26 mel bands, 1 output (onset activation)
// Config: ml-training/configs/onset_conv1d.yaml

#ifndef ONSET_MODEL_DATA_H
#define ONSET_MODEL_DATA_H

alignas(8) static const unsigned char onset_model_data[] = {
  0x00, 0x00, 0x00, 0x00
};

static const unsigned int onset_model_data_len = sizeof(onset_model_data);

#endif // ONSET_MODEL_DATA_H
