// Auto-generated by export_tflite.py — do not edit
// Placeholder stub — replace with trained RhythmNN model
// Expected: Conv1D+Pool, W192, 26 mel bands, 2 outputs (beat + downbeat)
// Config: ml-training/configs/rhythm_conv1d_pool.yaml

#ifndef RHYTHM_MODEL_DATA_H
#define RHYTHM_MODEL_DATA_H

alignas(8) static const unsigned char rhythm_model_data[] = {
  0x00, 0x00, 0x00, 0x00
};

static const unsigned int rhythm_model_data_len = sizeof(rhythm_model_data);

#endif // RHYTHM_MODEL_DATA_H
