#pragma once

// Generated by scripts/build.sh — do not edit manually.
// Build number is auto-incremented on each compile.
// See blinky-things/BUILD_NUMBER for the current value.

#define FIRMWARE_BUILD 132
#define FIRMWARE_VERSION "b132"
#define FIRMWARE_BUILD_DATE __DATE__ " " __TIME__
