#!/bin/bash
# Build firmware with auto-incrementing build number.
#
# Usage:
#   ./scripts/build.sh                    # compile only (nRF52840)
#   ./scripts/build.sh --upload PORT      # compile + upload via UF2
#   ./scripts/build.sh --esp32 [--upload PORT]  # ESP32-S3 target
#   ./scripts/build.sh --no-bump          # compile without incrementing
#
# The build number in blinky-things/BUILD_NUMBER is incremented on each
# compile and baked into the firmware via types/Version.h. This is the
# sole firmware version identifier — not tied to git tags or branches.
#
# Note: not safe for concurrent builds (two simultaneous runs could
# produce the same build number). Fine for single-developer use.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

BUMP=true
ESP32=false
UPLOAD=false
UPLOAD_PORT=""
OUTPUT_DIR="/tmp/blinky-build"
ARDUINO_CLI="${ARDUINO_CLI:-$(command -v arduino-cli 2>/dev/null || echo "$HOME/bin/arduino-cli")}"

while [[ $# -gt 0 ]]; do
    case $1 in
        --no-bump)   BUMP=false; shift ;;
        --esp32)     ESP32=true; shift ;;
        --upload)
            UPLOAD=true
            if [[ $# -lt 2 || "$2" == --* ]]; then
                echo "Error: --upload requires a port argument (e.g., --upload /dev/ttyACM0)" >&2
                exit 1
            fi
            UPLOAD_PORT="$2"; shift 2 ;;
        *)           echo "Unknown arg: $1"; exit 1 ;;
    esac
done

if ! command -v "$ARDUINO_CLI" >/dev/null 2>&1; then
    echo "Error: arduino-cli not found. Install it or set ARDUINO_CLI env var." >&2
    exit 1
fi

# --- Read build number ---
BUILD_FILE="blinky-things/BUILD_NUMBER"
BUILD=$(cat "$BUILD_FILE" | tr -d '[:space:]')
if ! [[ "$BUILD" =~ ^[0-9]+$ ]]; then
    echo "Error: BUILD_NUMBER is not a valid integer: '$BUILD'" >&2
    exit 1
fi

if $BUMP; then
    BUILD=$((BUILD + 1))
fi

# --- Generate Version.h ---
cat > blinky-things/types/Version.h << EOF
#pragma once

// Generated by scripts/build.sh — do not edit manually.
// Build number is auto-incremented on each compile.
// See blinky-things/BUILD_NUMBER for the current value.

#define FIRMWARE_BUILD $BUILD
#define FIRMWARE_VERSION "b$BUILD"
#define FIRMWARE_BUILD_DATE __DATE__ " " __TIME__
EOF

echo "=== Build $BUILD ==="

# --- Select FQBN ---
if $ESP32; then
    FQBN='esp32:esp32:XIAO_ESP32S3:USBMode=hwcdc,CDCOnBoot=default,MSCOnBoot=default,DFUOnBoot=default,UploadMode=default,CPUFreq=240,PSRAM=opi'
else
    FQBN='Seeeduino:nrf52:xiaonRF52840Sense'
fi

# --- Compile ---
COMPILE_ARGS=(
    compile
    --fqbn "$FQBN"
    --output-dir "$OUTPUT_DIR"
)

if $UPLOAD && $ESP32; then
    COMPILE_ARGS=(compile --upload --fqbn "$FQBN" -p "$UPLOAD_PORT")
fi

"$ARDUINO_CLI" "${COMPILE_ARGS[@]}" blinky-things

# Save build number only AFTER successful compile (no gaps on failure)
if $BUMP; then
    echo "$BUILD" > "$BUILD_FILE"
fi

echo "=== Build $BUILD complete ==="

# --- Upload via UF2 (nRF52840 only) ---
if $UPLOAD && ! $ESP32; then
    echo "=== Uploading to $UPLOAD_PORT via UF2 ==="
    python3 tools/uf2_upload.py "$UPLOAD_PORT" --firmware "$OUTPUT_DIR/blinky-things.ino.hex"
fi
