#!/bin/bash
# Build firmware with auto-incrementing build number.
#
# Usage:
#   ./scripts/build.sh                    # compile only (nRF52840)
#   ./scripts/build.sh --upload PORT      # compile + upload via UF2
#   ./scripts/build.sh --esp32 [--upload PORT]  # ESP32-S3 target
#   ./scripts/build.sh --no-bump          # compile without incrementing
#
# The build number in blinky-things/BUILD_NUMBER is incremented on each
# compile and baked into the firmware via types/Version.h. This is the
# sole firmware version identifier — not tied to git tags or branches.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

BUMP=true
ESP32=false
UPLOAD=false
UPLOAD_PORT=""
OUTPUT_DIR="/tmp/blinky-build"

while [[ $# -gt 0 ]]; do
    case $1 in
        --no-bump)   BUMP=false; shift ;;
        --esp32)     ESP32=true; shift ;;
        --upload)    UPLOAD=true; UPLOAD_PORT="$2"; shift 2 ;;
        *)           echo "Unknown arg: $1"; exit 1 ;;
    esac
done

# --- Bump build number ---
BUILD_FILE="blinky-things/BUILD_NUMBER"
BUILD=$(cat "$BUILD_FILE" | tr -d '[:space:]')

if $BUMP; then
    BUILD=$((BUILD + 1))
    echo "$BUILD" > "$BUILD_FILE"
fi

# --- Generate Version.h ---
cat > blinky-things/types/Version.h << EOF
#pragma once

// Generated by scripts/build.sh — do not edit manually.
// Build number is auto-incremented on each compile.
// See BUILD_NUMBER file for the current value.

#define FIRMWARE_BUILD $BUILD
#define FIRMWARE_VERSION "b$BUILD"
#define FIRMWARE_BUILD_DATE __DATE__ " " __TIME__
EOF

echo "=== Build $BUILD ==="

# --- Select FQBN ---
if $ESP32; then
    FQBN='esp32:esp32:XIAO_ESP32S3:USBMode=hwcdc,CDCOnBoot=default,MSCOnBoot=default,DFUOnBoot=default,UploadMode=default,CPUFreq=240,PSRAM=opi'
else
    FQBN='Seeeduino:nrf52:xiaonRF52840Sense'
fi

# --- Compile ---
COMPILE_ARGS=(
    compile
    --fqbn "$FQBN"
    --output-dir "$OUTPUT_DIR"
)

if $UPLOAD && $ESP32; then
    COMPILE_ARGS=(compile --upload --fqbn "$FQBN" -p "$UPLOAD_PORT")
fi

~/bin/arduino-cli "${COMPILE_ARGS[@]}" blinky-things

echo "=== Build $BUILD complete ==="

# --- Upload via UF2 (nRF52840 only) ---
if $UPLOAD && ! $ESP32; then
    echo "=== Uploading to $UPLOAD_PORT via UF2 ==="
    make uf2-upload UPLOAD_PORT="$UPLOAD_PORT"
fi
