#!/bin/bash
# Build firmware with auto-incrementing build number.
#
# Usage:
#   ./scripts/build.sh                    # compile only (nRF52840)
#   ./scripts/build.sh --upload PORT      # compile + upload via UF2
#   ./scripts/build.sh --esp32 [--upload PORT]  # ESP32-S3 target
#   ./scripts/build.sh --no-bump          # compile without incrementing
#
# The build number in blinky-things/BUILD_NUMBER is incremented on each
# compile and baked into the firmware via types/Version.h. This is the
# sole firmware version identifier — not tied to git tags or branches.
#
# Note: not safe for concurrent builds (two simultaneous runs could
# produce the same build number). Fine for single-developer use.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

BUMP=true
ESP32=false
UPLOAD=false
UPLOAD_PORT=""
OUTPUT_DIR="/tmp/blinky-build"
ARDUINO_CLI="${ARDUINO_CLI:-$(command -v arduino-cli 2>/dev/null || echo "$HOME/bin/arduino-cli")}"

while [[ $# -gt 0 ]]; do
    case $1 in
        --no-bump)   BUMP=false; shift ;;
        --esp32)     ESP32=true; shift ;;
        --upload)
            UPLOAD=true
            if [[ $# -lt 2 || "$2" == --* ]]; then
                echo "Error: --upload requires a port argument (e.g., --upload /dev/ttyACM0)" >&2
                exit 1
            fi
            UPLOAD_PORT="$2"; shift 2 ;;
        *)           echo "Unknown arg: $1"; exit 1 ;;
    esac
done

if ! command -v "$ARDUINO_CLI" >/dev/null 2>&1; then
    echo "Error: arduino-cli not found. Install it or set ARDUINO_CLI env var." >&2
    exit 1
fi

# --- Locate python (python3 on Linux/macOS, python on Windows) ---
PYTHON="${PYTHON:-$(command -v python3 2>/dev/null || command -v python 2>/dev/null || echo "python3")}"

# --- Locate Arduino15 packages directory (Linux: ~/.arduino15, Windows: %LOCALAPPDATA%/Arduino15) ---
if [[ -d "$HOME/.arduino15/packages" ]]; then
    ARDUINO15_PACKAGES="$HOME/.arduino15/packages"
elif [[ -n "${LOCALAPPDATA:-}" ]]; then
    # Windows (Git Bash / Cygwin): convert Windows path to Unix path
    if command -v cygpath >/dev/null 2>&1; then
        ARDUINO15_PACKAGES="$(cygpath -u "$LOCALAPPDATA")/Arduino15/packages"
    else
        # WSL or other: replace backslashes
        ARDUINO15_PACKAGES="${LOCALAPPDATA//\\//}/Arduino15/packages"
    fi
else
    ARDUINO15_PACKAGES=""
fi

# --- Verify TinyUSB CDC patch ---
# Critical: stock TinyUSB sets TX FIFO overwritable when DTR drops, which
# silently kills all serial output. The patch keeps FIFO non-overwritable.
# Without this patch, devices become unresponsive after any DTR transition
# (host serial port close, USB bus reset, server reconnection).
if ! $ESP32; then
    # Find CDC source across any installed core version (not hardcoded to 1.1.12)
    CDC_FILE=""
    if [[ -d "$ARDUINO15_PACKAGES/Seeeduino/hardware/nrf52" ]]; then
        CDC_FILE=$(find "$ARDUINO15_PACKAGES/Seeeduino/hardware/nrf52" \
            -path "*/Adafruit_TinyUSB_Arduino/src/class/cdc/cdc_device.c" \
            -print -quit 2>/dev/null || true)
    fi
    if [ -n "$CDC_FILE" ]; then
        # Assert the PATCHED line exists (fail-closed: if formatting changes, we catch it)
        if ! grep -Eq 'tu_fifo_set_overwritable\(&p_cdc->tx_ff,[[:space:]]*false\)' "$CDC_FILE"; then
            echo "ERROR: TinyUSB CDC patch not applied!" >&2
            echo "Stock TinyUSB drops all serial output when DTR is deasserted." >&2
            echo "Apply: patches/tinyusb-cdc-no-overwritable-fifo.patch" >&2
            echo "  File: $CDC_FILE" >&2
            echo "  Change: tu_fifo_set_overwritable(&p_cdc->tx_ff, !dtr)" >&2
            echo "      To: tu_fifo_set_overwritable(&p_cdc->tx_ff, false)" >&2
            exit 1
        fi
    else
        # Warn-only when file not found: allows compilation in CI environments
        # without the Arduino toolchain installed. On a dev machine with the
        # Seeeduino core, the file WILL be found and the patch WILL be enforced.
        echo "WARNING: TinyUSB CDC source not found — cannot verify patch." >&2
        echo "  Expected in: $ARDUINO15_PACKAGES/Seeeduino/hardware/nrf52/*/libraries/" >&2
    fi
fi

# --- Read build number ---
BUILD_FILE="blinky-things/BUILD_NUMBER"
BUILD=$(cat "$BUILD_FILE" | tr -d '[:space:]')
if ! [[ "$BUILD" =~ ^[0-9]+$ ]]; then
    echo "Error: BUILD_NUMBER is not a valid integer: '$BUILD'" >&2
    exit 1
fi

if $BUMP; then
    BUILD=$((BUILD + 1))
fi

# --- Generate Version.h ---
cat > blinky-things/types/Version.h << EOF
#pragma once

// Generated by scripts/build.sh — do not edit manually.
// Build number is auto-incremented on each compile.
// See blinky-things/BUILD_NUMBER for the current value.

#define FIRMWARE_BUILD $BUILD
#define FIRMWARE_VERSION "b$BUILD"
#define FIRMWARE_BUILD_DATE __DATE__ " " __TIME__
EOF

echo "=== Build $BUILD ==="

# --- Select FQBN ---
if $ESP32; then
    FQBN='esp32:esp32:XIAO_ESP32S3:USBMode=hwcdc,CDCOnBoot=default,MSCOnBoot=default,DFUOnBoot=default,UploadMode=default,CPUFreq=240,PSRAM=opi'
else
    FQBN='Seeeduino:nrf52:xiaonRF52840Sense'
fi

# --- Compile ---
COMPILE_ARGS=(
    compile
    --fqbn "$FQBN"
    --output-dir "$OUTPUT_DIR"
)

if $UPLOAD && $ESP32; then
    COMPILE_ARGS=(compile --upload --fqbn "$FQBN" -p "$UPLOAD_PORT")
fi

"$ARDUINO_CLI" "${COMPILE_ARGS[@]}" blinky-things

# Save build number only AFTER successful compile (no gaps on failure)
if $BUMP; then
    echo "$BUILD" > "$BUILD_FILE"
fi

echo "=== Build $BUILD complete ==="

# --- Upload via UF2 (nRF52840 only) ---
if $UPLOAD && ! $ESP32; then
    echo "=== Uploading to $UPLOAD_PORT via UF2 ==="
    # Windows: uf2_upload.py uses Linux-specific drive detection (lsblk, udisksctl).
    # Use uf2_upload_win.py instead — it detects the XIAO-SENSE drive via Win32_Volume.
    # NOTE: On Windows the software bootloader trigger (serial command / 1200-baud touch)
    # is unreliable because the Windows USB host power-cycles the port after
    # NVIC_SystemReset(), clearing the RAM magic before the bootloader can read it.
    # Double-tap the reset button on the device before running with --upload, then
    # re-run with --upload to copy the UF2 to the already-mounted XIAO-SENSE drive.
    if [[ -n "${LOCALAPPDATA:-}" ]]; then
        "$PYTHON" tools/uf2_upload_win.py "$UPLOAD_PORT" --build-dir "$OUTPUT_DIR"
    else
        "$PYTHON" tools/uf2_upload.py "$UPLOAD_PORT" --build-dir "$OUTPUT_DIR"
    fi
fi
